spring:
    application:
        name: payment

    # database
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: ${POSTGRESQL_USERNAME}
        password: ${POSTGRESQL_PASSWORD}
    # jpa properties
    jpa:
        hibernate:
            ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        generate-ddl: true

    # thymeleaf
    thymeleaf:
        suffix: .html
        cache: false

    # redis
    data:
        redis:
            host: ${REDIS_HOST}
            port: 6379

# custom
payments:
    redirectUrl: http://localhost:8080/payments/approve